export const contentGenres = [
 /* { id: 28, name: 'Acción', type: 'movie' },
  { id: 12, name: 'Aventura', type: 'both' },
  { id: 16, name: 'Animación', type: 'both' },
  { id: 35, name: 'Comedia', type: 'both' },
  { id: 80, name: 'Crimen', type: 'both' },
  { id: 99, name: 'Documental', type: 'both' },
  { id: 18, name: 'Drama', type: 'both' },
  { id: 10751, name: 'Familia', type: 'both' },
  { id: 14, name: 'Fantasía', type: 'both' },
  { id: 36, name: 'Historia', type: 'movie' },
  { id: 27, name: 'Terror', type: 'both' },
  { id: 10402, name: 'Música', type: 'movie' },
  { id: 9648, name: 'Misterio', type: 'both' },
  { id: 10749, name: 'Romance', type: 'both' },
  { id: 878, name: 'Ciencia ficción', type: 'both' },
  { id: 10770, name: 'Película TV', type: 'movie' },
  { id: 53, name: 'Suspenso', type: 'both' },
  { id: 10752, name: 'Bélica', type: 'movie' },
  { id: 37, name: 'Western', type: 'movie' },
  { id: 10759, name: 'Acción y Aventura', type: 'tv' },
  { id: 10762, name: 'Kids', type: 'tv' },
  { id: 10763, name: 'Noticias', type: 'tv' },
  { id: 10764, name: 'Reality', type: 'tv' },
  { id: 10765, name: 'Sci-Fi & Fantasía', type: 'tv' },
  { id: 10766, name: 'Soap', type: 'tv' },
  { id: 10767, name: 'Talk', type: 'tv' },
  { id: 10768, name: 'Guerra & Política', type: 'tv' } */
  { id: 28, name: 'Acción'},
  { id: 12, name: 'Aventura' },
  { id: 16, name: 'Animación' },
  { id: 35, name: 'Comedia' },
  { id: 80, name: 'Crimen'},
  { id: 99, name: 'Documental' },
  { id: 18, name: 'Drama' },
  { id: 10751, name: 'Familia' },
  { id: 14, name: 'Fantasía' },
  { id: 36, name: 'Historia' },
  { id: 27, name: 'Terror' },
  { id: 10402, name: 'Música' },
  { id: 9648, name: 'Misterio' },
  { id: 10749, name: 'Romance'},
  { id: 878, name: 'Ciencia ficción'},
  { id: 10770, name: 'Película TV'},
  { id: 53, name: 'Suspenso'},
  { id: 10752, name: 'Bélica'},
  { id: 37, name: 'Western'},
  { id: 10759, name: 'Acción y Aventura'},
  { id: 10762, name: 'Kids'},
  { id: 10763, name: 'Noticias'},
  { id: 10764, name: 'Reality'},
  { id: 10765, name: 'Sci-Fi & Fantasía'},
  { id: 10766, name: 'Soap' },
  { id: 10767, name: 'Talk'},
  { id: 10768, name: 'Guerra & Política'} 
];
